version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  mqtt-broker-data: {}
  grafana-storage: {}