apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://172.17.0.1:8086
    jsonData:
      version: Flux
      organization: cm-project
      defaultBucket: cm-project
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}