{
 "title": "Teste",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_name",
    "label": "Device Name",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.tagValues(\n  bucket: \"cm-project\",\n  tag: \"device\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput ${device_name}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"cm-project\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cm-project\")\n  |> filter(fn: (r) => r[\"device\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"command\"] == \"throughput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RTT ${device_name}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"cm-project\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cm-project\")\n  |> filter(fn: (r) => r[\"device\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"command\"] == \"rtt\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Led Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"cm-project\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"cm-project\")\n|> filter(fn: (r) => r[\"device\"] == \"${device_name}\")\n|> filter(fn: (r) => r[\"command\"] == \"led_status\")\n|> filter(fn: (r) => r[\"_field\"] == \"value\")\n|> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> yield(name: \"last\")"
    }
   ]
  }
 ]
}